/*
 * CMake autogenerated config.h file.
 * Make changes to config.h.cmake instead of this file.
 */

/***************************************************************************
 * Copyright (C) 2010 by Robert G. Jakabosky <bobby@sharedrealm.com>       *
 *                                                                         *
 ***************************************************************************/

#ifndef __LUA_GIT2_CONFIG_H__
#define __LUA_GIT2_CONFIG_H__

/* libgit2 feature support */
#cmakedefine HAVE_git_repository_open_no_backend

#endif /* __LUA_GIT2_CONFIG_H__ */
